version: '3'

services:
  ebac-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - D:/EBAC/Back-end/docker/arquivos_docker:/var/lib/postgresql/data
    networks:
      - postgres-ebac-network

  ebac-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "clark@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - ebac-postgres-compose
    networks:
      - postgres-ebac-network

  ebac-mysql-compose:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: 'vendas_online'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    ports:
      - "3306:3306"

  # ðŸ”µ MONGO ADICIONADO AQUI
  mongo-compose:
    image: mongo
    container_name: tarefaMod42
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: triti123
      MONGO_INITDB_ROOT_PASSWORD: triti123
    volumes:
      - mongo-data:/data/db
    networks:
      - postgres-ebac-network

  # ðŸ”µ MONGO EXPRESS (opcional para gerenciar via navegador)
  mongo-express-compose:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo-compose
    networks:
      - postgres-ebac-network

networks:
  postgres-ebac-network:
    driver: bridge

volumes:
  mongo-data:
